### ISSUE TITLE
D4 - Implemented Requirements

### ISSUE THREAD

**Issue by rjb489** [rjb489/CS386-wkgOut#97]
List in this section, the requirements and associated pull request that you implemented for this release, following the example below---include the description of the requirement, a link to the issue, a link to the pull request(s) that implement the requirement, who implemented the requirement, who approved it, and a print screen that depicts the implemented feature (if applicable). I expect that you implement the features you specified in your MVP (c.f. D.2 Requirements). 

Order the requirements below by the name of the student who implemented them. All the members of the group should have worked on implementation activities and submitted pull requests. Only stable code should be included in the release. The code that is still under development should be in branches. See the example:

EXAMPLE:
Requirement: As a Student, I want to add a homework assignment so that I can organize my ToDo list.

Issue: *link to GitHub Issue*

Pull request: *Link it here*

Implemented by: Martin Fowler

Approved by: Ada Lovelace

Print screen: A print screen that depicts the implemented feature (if applicable)

**Comment by chd63** [comment]
assignment was turned in so I am closing the issue
